security:
    encoders:
        UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_LECTURER:    [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database_users:
            entity:
                class: UserBundle:User

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
      - { path: ^/api/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/user/lecturers, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/workshops, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/news, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }